Repository discordjs/builders, pull requests merged in 2021-07, with the labels that each got.

#4 feat(Formatters): added `hyperlink` and `hideLinkEmbed`
  src/messages/formatters.ts
  tests/messages.test.ts
Labels: semver:minor

#5 feat: shrug, tableflip and unflip strings
  src/messages/formatters.ts
  tests/messages.test.ts
Labels: semver:minor

#7 test: massively speed up tests
  babel.config.js
  jest.config.js
  package-lock.json
  package.json
Labels: tests

#8 chore: improve tsconfig.json
  package.json
  src/tsconfig.json
  tsconfig.base.json
  tsconfig.eslint.json
  tsconfig.json
Labels: chore

#3 feat(SlashCommands): add slash command builders
  README.md
  babel.config.js
  docs/examples/Slash Command Builders.md
  jest.config.js
  package-lock.json
  package.json
  src/index.ts
  src/interactions/slashCommands/Assertions.ts
  src/interactions/slashCommands/SlashCommandBuilder.ts
  src/interactions/slashCommands/SlashCommandSubCommands.ts
  src/interactions/slashCommands/mixins/CommandOptionBase.ts
  src/interactions/slashCommands/mixins/CommandOptionWithChoices.ts
  src/interactions/slashCommands/mixins/CommandOptions.ts
  src/interactions/slashCommands/mixins/NameAndDescription.ts
  src/interactions/slashCommands/options/boolean.ts
  src/interactions/slashCommands/options/channel.ts
  src/interactions/slashCommands/options/integer.ts
  src/interactions/slashCommands/options/mentionable.ts
  src/interactions/slashCommands/options/role.ts
  src/interactions/slashCommands/options/string.ts
  src/interactions/slashCommands/options/user.ts
  tests/SlashCommands.test.ts
Labels: semver:minor

#14 fix(Shrug): Update comment
  src/messages/formatters.ts
Labels: documentation

#15 chore: update discord-api-types to 0.19.0
  package-lock.json
  package.json
  src/interactions/slashCommands/Assertions.ts
  src/interactions/slashCommands/SlashCommandBuilder.ts
  src/interactions/slashCommands/SlashCommandSubCommands.ts
  src/interactions/slashCommands/mixins/CommandOptionBase.ts
  src/interactions/slashCommands/mixins/CommandOptionWithChoices.ts
  src/interactions/slashCommands/options/boolean.ts
  src/interactions/slashCommands/options/channel.ts
  src/interactions/slashCommands/options/integer.ts
  src/interactions/slashCommands/options/mentionable.ts
  src/interactions/slashCommands/options/role.ts
  src/interactions/slashCommands/options/string.ts
  src/interactions/slashCommands/options/user.ts
Labels: dependencies, semver:patch

#16 feat(Formatters): Add a spoiler function
  src/messages/formatters.ts
  tests/messages.test.ts
Labels: semver:minor
