Repository discordjs/builders, pull requests merged in 2021-12, with the labels that each got.

#53 feat(SlashCommandBuilder): add autocomplete
  __tests__/SlashCommands.test.ts
  src/interactions/slashCommands/mixins/CommandOptionWithChoices.ts
  src/interactions/slashCommands/mixins/CommandOptions.ts
Labels: semver:minor

#47 feat: add max/min option for int and number builder options
  __tests__/SlashCommands.test.ts
  src/interactions/slashCommands/mixins/CommandNumberOptionBase.ts
  src/interactions/slashCommands/options/integer.ts
  src/interactions/slashCommands/options/number.ts
Labels: semver:minor

#66 fix: use zod instead of ow for max/min option validation
  src/interactions/slashCommands/options/integer.ts
  src/interactions/slashCommands/options/number.ts
Labels: refactor, semver:patch

#59 chore: update dapi types and fix errors
  package-lock.json
  package.json
  src/interactions/slashCommands/mixins/CommandChannelOptionBase.ts
  src/interactions/slashCommands/mixins/CommandOptionBase.ts
  src/interactions/slashCommands/mixins/CommandOptionWithChoices.ts
Labels: chore, semver:patch

#68 fix(ApplicationCommandOptions): clean up code for builder options
  __tests__/SlashCommands.test.ts
  package-lock.json
  package.json
  src/interactions/slashCommands/Assertions.ts
  src/interactions/slashCommands/SlashCommandBuilder.ts
  src/interactions/slashCommands/SlashCommandSubcommands.ts
  src/interactions/slashCommands/mixins/ApplicationCommandNumericOptionMinMaxValueMixin.ts
  src/interactions/slashCommands/mixins/ApplicationCommandOptionBase.ts
  src/interactions/slashCommands/mixins/ApplicationCommandOptionChannelTypesMixin.ts
  src/interactions/slashCommands/mixins/ApplicationCommandOptionWithChoicesAndAutocompleteMixin.ts
  src/interactions/slashCommands/mixins/CommandChannelOptionBase.ts
  src/interactions/slashCommands/mixins/CommandNumberOptionBase.ts
  src/interactions/slashCommands/mixins/CommandOptionBase.ts
  src/interactions/slashCommands/mixins/SharedSlashCommandOptions.ts
  src/interactions/slashCommands/options/boolean.ts
  src/interactions/slashCommands/options/channel.ts
  src/interactions/slashCommands/options/integer.ts
  src/interactions/slashCommands/options/mentionable.ts
  src/interactions/slashCommands/options/number.ts
  src/interactions/slashCommands/options/role.ts
  src/interactions/slashCommands/options/string.ts
  src/interactions/slashCommands/options/user.ts
Labels: dependencies, refactor, semver:major, typings

#69 fix(ApplicationCommandOptions): ensure toJSON return is valid
  __tests__/interactions/ContextMenuCommands.test.ts
  __tests__/interactions/SlashCommands/Options.test.ts
  __tests__/interactions/SlashCommands/SlashCommands.test.ts
  src/interactions/slashCommands/mixins/ApplicationCommandNumericOptionMinMaxValueMixin.ts
  src/interactions/slashCommands/mixins/NameAndDescription.ts
  src/interactions/slashCommands/options/integer.ts
  src/interactions/slashCommands/options/number.ts
Labels: semver:patch, tests
