Repository discordjs/builders, pull requests merged in 2021-08, with the labels that each got.

#17 chore(Deps): update `discord-api-types`
  package-lock.json
  package.json
  src/interactions/slashCommands/SlashCommandSubCommands.ts
Labels: dependencies

#18 refactor: `sub command` => `subcommand`
  docs/examples/Slash Command Builders.md
  src/index.ts
  src/interactions/slashCommands/Assertions.ts
  src/interactions/slashCommands/SlashCommandBuilder.ts
  src/interactions/slashCommands/SlashCommandSubcommands.ts
  src/interactions/slashCommands/mixins/CommandOptions.ts
  tests/SlashCommands.test.ts
Labels: refactor, semver:major

#20 feat(Formatters): add `formatEmoji`
  src/messages/formatters.ts
  tests/messages.test.ts
Labels: semver:minor

#21 refactor: remove return tsdoc
  src/messages/formatters.ts
Labels: documentation

#26 fix(SlashCommandBuilder): allow subcommands and groups to coexist at the root level
  src/interactions/slashCommands/SlashCommandBuilder.ts
  tests/SlashCommands.test.ts
Labels: semver:patch

#23 feat(SlashCommands): add number option type
  src/index.ts
  src/interactions/slashCommands/mixins/CommandOptionWithChoices.ts
  src/interactions/slashCommands/mixins/CommandOptions.ts
  src/interactions/slashCommands/options/number.ts
  tests/SlashCommands.test.ts
Labels: semver:minor

#19 feat(SlashCommandBuilder): create setDefaultPermission function
  src/interactions/slashCommands/Assertions.ts
  src/interactions/slashCommands/SlashCommandBuilder.ts
  tests/SlashCommands.test.ts
Labels: semver:minor

#11 feat: create `Embed` builder
  src/index.ts
  src/messages/embed/Assertions.ts
  src/messages/embed/Embed.ts
  tests/messages/embed.test.ts
  tests/messages/formatters.test.ts
Labels: feature request, semver:minor

#34 fix: properly type `toJSON` methods
  src/interactions/slashCommands/SlashCommandBuilder.ts
  src/interactions/slashCommands/SlashCommandSubcommands.ts
Labels: semver:patch
